# Site settings
title: Sam Tang
email: sam@thesamtang.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright © 2015 Sam Tang
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thesamtang.com" # the base hostname & protocol for your site
twitter_username: thesamtang
github_username:  thesamtang

# Build settings
markdown: kramdown
